import { DripGuardResult } from '../core/types.js';

export const PR_COMMENT_ANCHOR = '<!-- dripguard-report -->';

export function formatMarkdownReport(result: DripGuardResult): string {
  const lines: string[] = [];

  lines.push(PR_COMMENT_ANCHOR);
  lines.push('## 💧 DripGuard Funding Health Report');
  lines.push('');

  const isPass = result.status === 'pass';
  const isWarn = result.status === 'warn';
  const badge = isPass
    ? '✅ **Status: PASS**'
    : isWarn
    ? '⚠️ **Status: PASS (with warnings)**'
    : '❌ **Status: FAILED (policy violations)**';

  lines.push(badge);
  lines.push('');
  lines.push(`**Repository:** \`${result.repository}\` ${result.commitSha ? `(${result.commitSha.substring(0, 7)})` : ''} | **Provider:** \`${result.providerMode}\``);
  lines.push('');

  // Funding Coverage Table
  lines.push('### Funding Coverage');
  lines.push('');
  lines.push('| Metric | Result | Target |');
  lines.push('|:---|---:|---:|');
  lines.push(`| Total Applicable Dependencies | ${result.coverage.totalDependencies} | - |`);
  lines.push(`| Canonical Projects Mapped | ${result.coverage.resolvedDependencies} | - |`);
  lines.push(`| Verified Funded on Drips | ${result.coverage.fundedDependencies} | - |`);
  lines.push(`| Unfunded Dependencies | ${result.coverage.unfundedDependencies} | 0 |`);
  if (result.coverage.exemptDependencies > 0) {
    lines.push(`| Policy Exemptions | ${result.coverage.exemptDependencies} | - |`);
  }
  lines.push(`| **Overall Coverage** | **${result.coverage.coveragePercent}%** | **90%** |`);
  if (result.coverage.directTotal > 0) {
    lines.push(`| **Direct Dependency Coverage** | **${result.coverage.directCoveragePercent}%** | **100%** |`);
  }
  lines.push('');

  // Drift Section
  if (result.drift && (result.drift.addedDependencies.length > 0 || result.drift.removedDependencies.length > 0)) {
    lines.push('### 🔄 Funding Drift vs Baseline');
    lines.push('');

    if (result.drift.newUnfundedDependencies.length > 0) {
      lines.push('#### ❌ Newly Added Unfunded Dependencies');
      for (const d of result.drift.newUnfundedDependencies) {
        const repo = d.resolvedDependency.project
          ? `[${d.resolvedDependency.project.owner}/${d.resolvedDependency.project.repository}](${d.resolvedDependency.project.url})`
          : '*(unresolved repository)*';
        lines.push(`- \`${d.resolvedDependency.dependency.name}\` (${d.resolvedDependency.dependency.ecosystem}) → ${repo}`);
      }
      lines.push('');
    }

    if (result.drift.addedDependencies.length > 0) {
      lines.push(`<details><summary><b>Added Dependencies (${result.drift.addedDependencies.length})</b></summary>`);
      lines.push('');
      for (const d of result.drift.addedDependencies) {
        const repo = d.project ? `[${d.project.owner}/${d.project.repository}](${d.project.url})` : 'unresolved';
        lines.push(`- \`${d.dependency.name}\` (${d.dependency.version || 'any'}) → ${repo}`);
      }
      lines.push('</details>');
      lines.push('');
    }

    if (result.drift.removedDependencies.length > 0) {
      lines.push(`<details><summary><b>Removed Dependencies (${result.drift.removedDependencies.length})</b></summary>`);
      lines.push('');
      for (const d of result.drift.removedDependencies) {
        lines.push(`- \`${d.dependency.name}\` (${d.dependency.ecosystem})`);
      }
      lines.push('</details>');
      lines.push('');
    }
  }

  // Concentration Section
  if (result.concentration && result.concentration.maxSingleRecipient.sharePercent > 0) {
    const top = result.concentration.maxSingleRecipient;
    const topName = top.project ? `[${top.project.owner}/${top.project.repository}](${top.project.url})` : `\`${top.receiver}\``;
    lines.push('### 📊 Funding Concentration & Diversity');
    lines.push('');
    lines.push(`- **Top Recipient:** ${topName} receives **${top.sharePercent.toFixed(1)}%** of allocated funds.`);
    lines.push(`- **Diversity Index (HHI):** \`${result.concentration.herfindahlHirschmanIndex}\` (effective diversity: ~${result.concentration.effectiveRecipientsCount.toFixed(1)} projects)`);
    lines.push('');
  }

  // Violations Section
  if (result.violations.length > 0) {
    lines.push('### ⚠️ Policy Violations');
    lines.push('');
    for (const v of result.violations) {
      lines.push(`- ❌ **\`${v.rule}\`**: ${v.message}`);
    }
    lines.push('');
  }

  // Warnings Section
  if (result.warnings.length > 0) {
    lines.push('### ℹ️ Policy Warnings');
    lines.push('');
    for (const w of result.warnings) {
      lines.push(`- ⚠️ **\`${w.rule}\`**: ${w.message}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by [DripGuard](https://github.com/Stephan-Thomas/DripGuard) • Evaluated in ${result.executionDurationMs}ms*`);

  return lines.join('\n');
}
